name: stepflow
description: |
  Dart package that provides a structural base for creating step-based, 
  modular workflows inside of applications.

version: 2.0.0
repository: https://github.com/zopnote/stepflow

environment:
  sdk: ^3.6.2

dependencies:
  meta: ^1.17.0
  path: ^1.9.1
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.24.0

